Fix bug logger; Fix GrantedAuthorities; Fix loadScript tag; fix UUID copy to Clipboard JS;

diff --git a/bin/build b/bin/build
--- a/bin/build
+++ b/bin/build
@@ -7,7 +7,7 @@ loc_sources=/Users/georg/poormanscastle/sources/
 loc_projects=/Users/georg/poormanscastle/projects/
 # define locations of tomcat instances running the timeo modules.
 # loc_tc_userservice means location of tomcat running userservice ;-)
-loc_tc_userservice=
+loc_tc_userservice=${loc_opt}timeo-userservice/
 loc_tc_stakeholderservice=${loc_opt}timeo-stakeholderservice/
 loc_tc_taskservice=${loc_opt}timeo-taskservice/
 loc_tc_cas=
@@ -31,6 +31,10 @@ if [ ! -d ${loc_tc_taskservice} ]; then
   echo "tomcat for task service not found: ${loc_tc_taskservice}. Please check system setup and then run build script again."
   exit 1
 fi
+if [ ! -d ${loc_tc_userservice} ]; then
+  echo "tomcat for user service not found: ${loc_tc_userservice}. Please check system setup an then run build script again."
+  exit 1
+fi
 echo "Shutting down stakeholder service"
 pushd ${loc_tc_stakeholderservice}
 bin/shutdown.sh
@@ -40,6 +44,11 @@ echo "Shutting down task service"
 pushd ${loc_tc_taskservice}
 bin/shutdown.sh
 rm -rf webapps/timeo-taskservice*
+popd
+echo "Shutting down user service"
+pushd ${loc_tc_userservice}
+bin/shutdown.sh
+rm -rf webapps/timeo-userservice*
 popd
 
 # TODO shutdown the other services as they become available
@@ -60,9 +69,11 @@ mvn -P ${stage} clean package
 
 # then, copy the war files
 echo "Copying stakeholder service war to tomcat webapps"
-cp -v timeo-stakeholderservice/target/timeo-stakeholderservice.war ${loc_tc_stakeholderservice}webapps
+cp -v timeo-stakeholderservice/target/timeo-stakeholderservice.war ${loc_tc_stakeholderservice}webapps/
 echo "Copying task service war file to tomcat webapps"
-cp -v timeo-taskservice/target/timeo-taskservice.war ${loc_tc_taskservice}webapps
+cp -v timeo-taskservice/target/timeo-taskservice.war ${loc_tc_taskservice}webapps/
+echo "Copying user service war file to tomcat webapps"
+cp -v timeo-userservice/target/timeo-userservice.war ${loc_tc_userservice}webapps/
 
 # now, enough time should have passed to restart the services
 echo "Restarting stakeholder service tomcat."
@@ -71,6 +82,10 @@ bin/startup.sh
 popd
 echo "Restarting task service tomcat."
 pushd ${loc_tc_taskservice}
+bin/startup.sh
+popd
+echo "Restarting user service tomcat."
+pushd ${loc_tc_userservice}
 bin/startup.sh
 popd
 
